server:
  port: 8080

spring:
  application:
    name: CLIENT

eureka:
  client:
    #分区
    region: suyu
    availability-zones:
      suyu: e1
    prefer-same-zone-eureka: true
    service-url:
      e1: http://localhost:7900/eureka/,http://localhost:7901/eureka/
      e2: http://localhost:7902/eureka/,http://localhost:7903/eureka/
  instance:
    #hostname: localhost
    #将自己的ip地址显示在EUREKA服务上，不配置或false表示将所在操作系统hostname注册到EUREKA
    prefer-ip-address: true
    #ip地址
    ip-address: 127.0.0.1
    #服务刷新时间设置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 30
    #服务过期时间配置，超过这个时间没有接收到EUREKA就会将这个实例剔除
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      zone: e1

zone:
  name: suyu-e1

